# db/Dockerfile
FROM postgres:18

RUN apt-get update && apt-get install -y --fix-missing \
    curl \
    ca-certificates \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN install -d /usr/share/postgresql-common/pgdg && \
    curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc

RUN . /etc/os-release && \
    sh -c "echo 'deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main' > /etc/apt/sources.list.d/pgdg.list"

RUN . /etc/os-release && \
    curl -fsSL https://packages.groonga.org/debian/groonga-archive-keyring.gpg \
    | gpg --dearmor -o /usr/share/keyrings/groonga-archive-keyring.gpg && \
    sh -c "echo 'deb [signed-by=/usr/share/keyrings/groonga-archive-keyring.gpg] https://packages.groonga.org/debian/ ${VERSION_CODENAME} main' > /etc/apt/sources.list.d/groonga.list"

RUN apt-get update && apt-get install -y --fix-missing \
    git \
    make \
    gcc \
    postgresql-server-dev-18 \
    postgresql-18-pgdg-pgroonga \
    && cd /tmp \
    && git clone --branch v0.8.1 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && cd .. \
    && rm -rf pgvector \
    && apt-get remove -y git make gcc postgresql-server-dev-18 curl ca-certificates gnupg \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*